// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFYeoWHd3D515XRiMZhPjPsn38zRni7A8',
    appId: '1:519394515243:android:86897458bb28244c0ccd6e',
    messagingSenderId: '519394515243',
    projectId: 'letzcare-app',
    storageBucket: 'letzcare-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkLu2VtxQJPYcQBaRiJT75C5A4KVGy5B0',
    appId: '1:519394515243:ios:13395d5c79222a370ccd6e',
    messagingSenderId: '519394515243',
    projectId: 'letzcare-app',
    storageBucket: 'letzcare-app.appspot.com',
    iosClientId: '519394515243-oral030n173d1k5l336a3ki55b4dvtnd.apps.googleusercontent.com',
    iosBundleId: 'com.letzcare.app.letzcqre',
  );
}
